package kop.ui;

import com.bbn.openmap.MapBean;
import kop.Main;
import kop.game.Game;
import kop.game.GameStateListener;
import kop.map.MapBeanFactory;
import org.geotools.map.MapLayer;
import org.geotools.swing.JMapPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import static kop.Main.*;

/**
 * Created by IntelliJ IDEA.
 * User: ola
 * Date: 4/3/11
 * Time: 2:01 PM
 * To change this template use File | Settings | File Templates.
 */
public class MainWindow implements KopWindow, GameStateListener {
	private JToggleButton startButton;
	private JButton displayShips;
	private JPanel contentPane;
	private JButton newShip;
	private JButton companyInfo;
	private MapBean mapBean;
	private JLabel currentDate;
	private JMapPane mapPane;
	private JLabel currentMoney;
	private MapLayer shipLayer;
	private Logger logger = null;

	public MainWindow() {
		$$$setupUI$$$();
		logger = LoggerFactory.getLogger(this.getClass());

		displayShips.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				displayFrame(new CompanyShipsWindow());
			}
		});
		newShip.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				displayFrame(new NewShipWindow());
			}
		});
		companyInfo.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				displayFrame(new CompanyInfoWindow());
			}
		});
		startButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				if (startButton.getModel().isSelected()) {
					logger.info("Selected");
					startButton.setText("STOP");
				} else {
					logger.info("Not selected");
					startButton.setText("START");
				}
			}
		});
	}

	public JPanel getContentPane() {
		return contentPane;
	}

	@Override
	public String getTitle() {
		return "Main window";  //To change body of implemented methods use File | Settings | File Templates.
	}

	private void createUIComponents() {
		MapBeanFactory mapBeanFactory = new MapBeanFactory();
		mapBean = mapBeanFactory.createOpenMapBean();
		mapBean.setVisible(false);

		currentDate = new JLabel();
		currentMoney = new JLabel();
		mapPane = mapBeanFactory.createGeoToolsBean();
		for (MapLayer layer : mapPane.getMapContext().getLayers()) {
			if (layer.getTitle().equals(MapBeanFactory.SHIP_LAYER)) {
				shipLayer = layer;
			}
		}
		stateChanged();
	}

	@Override
	public void stateChanged() {
		currentDate.setText(Game.getInstance().getCurrentDateAsString());
		currentMoney.setText(String.valueOf(Game.getInstance().getPlayerCompany().getMoney()));
	}

	public static void main(String[] args) {
		Game.getInstance().getPlayerCompany().setMoney(1000000000);
		Main.displayFrame(new MainWindow());
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		contentPane = new JPanel();
		contentPane.setLayout(new GridBagLayout());
		displayShips = new JButton();
		displayShips.setText("Show ships");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 7;
		gbc.gridy = 6;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		contentPane.add(displayShips, gbc);
		newShip = new JButton();
		newShip.setText("New ship");
		gbc = new GridBagConstraints();
		gbc.gridx = 7;
		gbc.gridy = 3;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		contentPane.add(newShip, gbc);
		startButton = new JToggleButton();
		startButton.setActionCommand("startButton");
		startButton.setHorizontalAlignment(0);
		startButton.setLabel("START");
		startButton.setText("START");
		startButton.setMnemonic('S');
		startButton.setDisplayedMnemonicIndex(0);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.gridheight = 5;
		gbc.weightx = 0.1;
		gbc.fill = GridBagConstraints.BOTH;
		gbc.ipadx = 10;
		contentPane.add(startButton, gbc);
		companyInfo = new JButton();
		companyInfo.setText("Company info");
		gbc = new GridBagConstraints();
		gbc.gridx = 7;
		gbc.gridy = 7;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		contentPane.add(companyInfo, gbc);
		final JLabel label1 = new JLabel();
		label1.setText("Current date and time:");
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 3;
		gbc.anchor = GridBagConstraints.WEST;
		contentPane.add(label1, gbc);
		gbc = new GridBagConstraints();
		gbc.gridx = 4;
		gbc.gridy = 3;
		gbc.anchor = GridBagConstraints.WEST;
		contentPane.add(currentDate, gbc);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridwidth = 8;
		gbc.fill = GridBagConstraints.BOTH;
		contentPane.add(mapBean, gbc);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.gridwidth = 8;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		contentPane.add(mapPane, gbc);
		final JLabel label2 = new JLabel();
		label2.setText("Current money:");
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 6;
		gbc.anchor = GridBagConstraints.WEST;
		contentPane.add(label2, gbc);
		currentMoney.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 5;
		gbc.gridy = 6;
		gbc.anchor = GridBagConstraints.WEST;
		contentPane.add(currentMoney, gbc);
		final JPanel spacer1 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 3;
		gbc.gridy = 7;
		gbc.weightx = 0.2;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		contentPane.add(spacer1, gbc);
		final JPanel spacer2 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 6;
		gbc.gridy = 7;
		gbc.weightx = 0.1;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		contentPane.add(spacer2, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}
}
