package kop.ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import kop.Main;
import kop.cargo.Freight;
import kop.company.Company;
import kop.game.Game;
import kop.game.GameTestUtil;
import kop.ports.NoSuchPortException;
import kop.ports.PortProxy;
import kop.ships.model.ShipModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableRowSorter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 * Created by IntelliJ IDEA.
 * User: ola
 * Date: 4/6/11
 * Time: 7:41 AM
 * To change this template use File | Settings | File Templates.
 */
public class PortWindow implements KopWindow {
	private PortProxy portProxy;
	private JLabel nameOfPort;
	private JTable portFreightTable;
	private JPanel contentPane;
	private JButton cancelButton;
	private JButton okButton;
	private JTable shipFreightTable;
	private JList shipsInPortListBox;
	private JLabel shipName;
	private JLabel shipType;
	private JLabel shipDWT;
	private JButton charterButton;
	private JLabel availableDWT;
	private FreightTableModel shipFreightTableModel;
	private FreightTableModel portFreightTableModel;
	private Logger logger;

	public PortWindow(PortProxy portProxy) {
		this.portProxy = portProxy;
		$$$setupUI$$$();
		logger = LoggerFactory.getLogger(this.getClass());

		shipsInPortListBox.addListSelectionListener(new ListSelectionListener() {
			@Override
			public void valueChanged(ListSelectionEvent e) {
				ShipModel selectedValue = (ShipModel) shipsInPortListBox.getSelectedValue();
				shipName.setText(selectedValue.getName());
				shipType.setText(selectedValue.getBlueprint().getType().toString());
				shipDWT.setText(String.valueOf(selectedValue.getDwt()));
				availableDWT.setText(String.valueOf(selectedValue.getAvailableDWT()));
				shipFreightTable.setModel(new FreightTableModel(selectedValue));
			}
		});
		charterButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				if (portFreightTable.getSelectedRow() == -1) {
					// TODO fire dialog
					return;
				}

				if (shipsInPortListBox.getSelectedIndex() == -1) {
					// TODO fire dialog
					return;
				}

				Freight f = portFreightTableModel.getFreightAtRow(portFreightTable.getSelectedRow());
				ShipModel ship = (ShipModel) shipsInPortListBox.getSelectedValue();

				// TODO add asserts, can the ship really take on the freight?
				// if not, add a part of the freight.
				Game.getInstance().getFreightMarket().loadFreightOntoShip(ship, f);
				logger.debug("Loaded %s on %s", f, ship);
			}
		});
	}

	@Override
	public JPanel getContentPane() {
		return contentPane;
	}

	@Override
	public String getTitle() {
		return String.format("Port %s", portProxy.getName());
	}

	private void createUIComponents() {

		portFreightTableModel = new FreightTableModel();
		portFreightTable = new JTable(portFreightTableModel);
		TableRowSorter<FreightTableModel> portTableSorter = new TableRowSorter<FreightTableModel>(portFreightTableModel);
		portFreightTable.setRowSorter(portTableSorter);
		portTableSorter.setRowFilter(new FreightTableModel.PortRowFilter(portProxy));

		Company playerCompany = Game.getInstance().getPlayerCompany();
		List<ShipModel> shipsInPortList = playerCompany.findShipsInPort(portProxy);

		shipsInPortListBox = new JList(shipsInPortList.toArray());

		// TODO this is fugly-hacked at the moment.
		FreightTableModel shipFreightTableModel = new FreightTableModel(shipsInPortList.get(0));
		shipFreightTable = new JTable(shipFreightTableModel);
		TableRowSorter<FreightTableModel> shipTableSorter = new TableRowSorter<FreightTableModel>(shipFreightTableModel);
		shipFreightTable.setRowSorter(shipTableSorter);

		nameOfPort = new JLabel();
		nameOfPort.setText(portProxy.getName());
	}

	public static void main(String[] args) {
		GameTestUtil.setupInstanceForTest();
		String portName = "Durban";
		try {
			Main.displayFrame(new PortWindow(Game.getInstance().getPortByName(portName).getProxy()));
		} catch (NoSuchPortException e) {
			Logger logger = LoggerFactory.getLogger(PortWindow.class);
			logger.error(String.format("Could not find port %s", portName), e);
		}
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		contentPane = new JPanel();
		contentPane.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:d:grow(0.5),left:4dlu:noGrow,fill:max(d;4px):grow(0.5),left:4dlu:noGrow,left:4dlu:noGrow", "center:221px:noGrow,top:5dlu:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
		CellConstraints cc = new CellConstraints();
		contentPane.add(nameOfPort, cc.xy(1, 5));
		final JScrollPane scrollPane1 = new JScrollPane();
		contentPane.add(scrollPane1, cc.xyw(5, 1, 3, CellConstraints.FILL, CellConstraints.FILL));
		scrollPane1.setViewportView(shipFreightTable);
		final JScrollPane scrollPane2 = new JScrollPane();
		contentPane.add(scrollPane2, cc.xywh(5, 7, 3, 13, CellConstraints.FILL, CellConstraints.FILL));
		scrollPane2.setViewportView(portFreightTable);
		final JScrollPane scrollPane3 = new JScrollPane();
		contentPane.add(scrollPane3, cc.xyw(9, 1, 3, CellConstraints.FILL, CellConstraints.FILL));
		shipsInPortListBox.setSelectionMode(0);
		scrollPane3.setViewportView(shipsInPortListBox);
		cancelButton = new JButton();
		cancelButton.setText("Cancel");
		cancelButton.setMnemonic('C');
		cancelButton.setDisplayedMnemonicIndex(0);
		contentPane.add(cancelButton, cc.xy(11, 21));
		charterButton = new JButton();
		charterButton.setText("Charter");
		charterButton.setMnemonic('T');
		charterButton.setDisplayedMnemonicIndex(4);
		contentPane.add(charterButton, cc.xy(7, 4));
		final JLabel label1 = new JLabel();
		label1.setText("Ship name");
		contentPane.add(label1, cc.xy(9, 7));
		final JLabel label2 = new JLabel();
		label2.setText("Ship type");
		contentPane.add(label2, cc.xy(9, 9));
		final JLabel label3 = new JLabel();
		label3.setText("Max DWT");
		contentPane.add(label3, cc.xy(9, 11));
		shipName = new JLabel();
		shipName.setText("Label");
		contentPane.add(shipName, cc.xy(11, 7, CellConstraints.LEFT, CellConstraints.DEFAULT));
		shipType = new JLabel();
		shipType.setText("Label");
		contentPane.add(shipType, cc.xy(11, 9, CellConstraints.LEFT, CellConstraints.DEFAULT));
		shipDWT = new JLabel();
		shipDWT.setText("Label");
		contentPane.add(shipDWT, cc.xy(11, 11, CellConstraints.LEFT, CellConstraints.DEFAULT));
		final JLabel label4 = new JLabel();
		label4.setText("Available DWT");
		contentPane.add(label4, cc.xy(9, 13));
		availableDWT = new JLabel();
		availableDWT.setText("Label");
		contentPane.add(availableDWT, cc.xy(11, 13));
		okButton = new JButton();
		okButton.setText("OK");
		okButton.setMnemonic('O');
		okButton.setDisplayedMnemonicIndex(0);
		contentPane.add(okButton, cc.xy(9, 21));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}
}
