package kop.ui;

import kop.Main;
import kop.game.GameTestUtil;

import javax.swing.*;
import javax.swing.table.TableRowSorter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by IntelliJ IDEA.
 * User: ola
 * Date: 4/6/11
 * Time: 7:42 AM
 * To change this template use File | Settings | File Templates.
 */
public class WorldFreightMarketWindow implements KopWindow {

	private JTable freightTable;
	private JButton closeButton;
	private JPanel contentPane;
	private boolean componentsCreated = false;

	public WorldFreightMarketWindow() {
		$$$setupUI$$$();
		if (!componentsCreated) {
			createUIComponents();
		}
		closeButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				Main.displayFrame(new MainWindow());
			}
		});
	}

	@Override
	public JPanel getContentPane() {
		return contentPane;  //To change body of implemented methods use File | Settings | File Templates.
	}

	@Override
	public String getTitle() {
		return null;  //To change body of implemented methods use File | Settings | File Templates.
	}

	private void createUIComponents() {
		FreightTableModel freightTableModel = new FreightTableModel();
		freightTable = new JTable(freightTableModel);
		TableRowSorter<FreightTableModel> sorter = new TableRowSorter<FreightTableModel>(freightTableModel);
		freightTable.setRowSorter(sorter);
		sorter.setRowFilter(null);
		componentsCreated = true;
	}

	public static void main(String[] args) {
		GameTestUtil.setupInstanceForTest();
		Main.displayFrame(new WorldFreightMarketWindow());
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		contentPane = new JPanel();
		contentPane.setLayout(new GridBagLayout());
		closeButton = new JButton();
		closeButton.setText("Close");
		closeButton.setMnemonic('C');
		closeButton.setDisplayedMnemonicIndex(0);
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		contentPane.add(closeButton, gbc);
		final JPanel spacer1 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.weightx = 0.8;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		contentPane.add(spacer1, gbc);
		final JScrollPane scrollPane1 = new JScrollPane();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridwidth = 2;
		gbc.weightx = 1.0;
		gbc.weighty = 0.9;
		gbc.fill = GridBagConstraints.BOTH;
		contentPane.add(scrollPane1, gbc);
		scrollPane1.setViewportView(freightTable);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}
}
